//images
import signinImage from "@/assets/login-image.png";
import signupImage from "@/assets/signup-image.png";
import ForgotImage from "@/assets/forgot-image.png";
import ResetImage from "@/assets/reset-image.png";
import avatarPlaceholder from "@/assets/avatar-placeholder.png";

// icons
import {
  AlertCircle as AlertCircleIcon,
  AlertTriangle as AlertTriangleIcon,
  ArrowLeft as ArrowLeftIcon,
  Bell as BellIcon,
  BookmarkIcon,
  Calendar as CalendarIcon,
  Camera as CameraIcon,
  CheckCheck as CheckCheckIcon,
  CheckCircle2 as CheckCircle2Icon,
  Check as CheckIcon,
  ChevronDown as ChevronDownIcon,
  ChevronLeft as ChevronLeftIcon,
  ChevronRight as ChevronRightIcon,
  ChevronUp as ChevronUpIcon,
  Circle as CircleIcon,
  X as CloseIcon,
  Compass as CompassIcon,
  Trash2 as DeleteIcon,
  Eye as EyeIcon,
  EyeOff as EyeOffIcon,
  FileText as FileTextIcon,
  Flame as FlameIcon,
  HeartIcon,
  Home as HomeIcon,
  ImageIcon,
  KeyRound as KeyRoundIcon,
  LayoutGrid as LayoutGridIcon,
  List as ListIcon,
  Loader2 as LoadingIcon,
  LogOutIcon,
  MailCheck as MailCheckIcon,
  Mail as MailIcon,
  MessageCircle as MessageCircleIcon,
  MessageSquareIcon,
  MessagesSquare as MessagesSquareIcon,
  Monitor as MonitorIcon,
  MoonIcon,
  MoreHorizontalIcon as OptionsIcon,
  Play as PlayIcon,
  RotateCcw as RotateCcwIcon,
  SearchIcon,
  SendHorizonal as SendHorizonalIcon,
  Send as SendIcon,
  ShieldCheck as ShieldCheckIcon,
  Sparkles as SparklesIcon,
  SunIcon,
  TrendingUp as TrendingUpIcon,
  User2 as User2Icon,
  UserCheck as UserCheckIcon,
  UserIcon,
  UserPlus as UserPlusIcon,
  Users as UsersIcon,
} from "lucide-react";

const ImageConfig = {
  signinImage,
  signupImage,
  ForgotImage,
  ResetImage,
  avatarPlaceholder,
  // icons
  AlertCircleIcon,
  AlertTriangleIcon,
  ArrowLeftIcon,
  BellIcon,
  BookmarkIcon,
  CalendarIcon,
  CameraIcon,
  CheckCheckIcon,
  CheckCircle2Icon,
  CheckIcon,
  ChevronDownIcon,
  ChevronLeftIcon,
  ChevronRightIcon,
  ChevronUpIcon,
  CircleIcon,
  CloseIcon,
  CompassIcon,
  DeleteIcon,
  EyeIcon,
  EyeOffIcon,
  FileTextIcon,
  FlameIcon,
  HeartIcon,
  HomeIcon,
  ImageIcon,
  KeyRoundIcon,
  LayoutGridIcon,
  ListIcon,
  LoadingIcon,
  LogOutIcon,
  MailCheckIcon,
  MailIcon,
  MessageCircleIcon,
  MessageSquareIcon,
  MessagesSquareIcon,
  MonitorIcon,
  MoonIcon,
  OptionsIcon,
  PlayIcon,
  RotateCcwIcon,
  SearchIcon,
  SendHorizonalIcon,
  SendIcon,
  ShieldCheckIcon,
  SparklesIcon,
  SunIcon,
  TrendingUpIcon,
  User2Icon,
  UserCheckIcon,
  UserIcon,
  UserPlusIcon,
  UsersIcon,
};

export {
  AlertCircleIcon,
  AlertTriangleIcon,
  ArrowLeftIcon,
  BellIcon,
  BookmarkIcon,
  CalendarIcon,
  CameraIcon,
  CheckCheckIcon,
  CheckCircle2Icon,
  CheckIcon,
  ChevronDownIcon,
  ChevronLeftIcon,
  ChevronRightIcon,
  ChevronUpIcon,
  CircleIcon,
  CloseIcon,
  CompassIcon,
  DeleteIcon,
  EyeIcon,
  EyeOffIcon,
  FileTextIcon,
  FlameIcon,
  HeartIcon,
  HomeIcon,
  ImageIcon,
  KeyRoundIcon,
  LayoutGridIcon,
  ListIcon,
  LoadingIcon,
  LogOutIcon,
  MailCheckIcon,
  MailIcon,
  MessageCircleIcon,
  MessageSquareIcon,
  MessagesSquareIcon,
  MonitorIcon,
  MoonIcon,
  OptionsIcon,
  PlayIcon,
  RotateCcwIcon,
  SearchIcon,
  SendHorizonalIcon,
  SendIcon,
  ShieldCheckIcon,
  SparklesIcon,
  SunIcon,
  TrendingUpIcon,
  User2Icon,
  UserCheckIcon,
  UserIcon,
  UserPlusIcon,
  UsersIcon,
};
export default ImageConfig;
